[package]
name = "macro-test"
version = "0.2.3"
description = "example macro crate for cargo-watt"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
